version: '3.8'
services:
server:
build: ./server
ports:
- "3000:3000"
environment:
- PORT=3000
volumes:
- /var/run/docker.sock:/var/run/docker.sock:ro
restart: unless-stopped
client:
build: ./client
ports:
- "5173:5173"
depends_on:
- server
restart: unless-stopped
